name: Release - Module

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: Release Version
        required: true
        default: 1.0.0

run-name: 'version set to ${{ inputs.release-version }} for release'

jobs:
  main:
    uses: codbex/codbex-infra/.github/workflows/module-release.yaml@main
    with:
      packages: codbex-rfqs,codbex-rfqs-data
      packages-build: codbex-rfqs
      release-version: ${{ inputs.release-version }}
      release-content: |
        ## codbex-rfqs - ${{ inputs.release-version }}
  
        RFQs Management Module
  
        ## Installation
  
        ```
        npm install @codbex/codbex-rfqs@${{ inputs.release-version }}
        npm install @codbex/codbex-rfqs-data@${{ inputs.release-version }}
        ```
  
        ## Access points:
  
        - [/services/web/codbex-rfqs/gen/](http://localhost:80/services/web/codbex-rfqs/gen/) - Admin Panel
    secrets: inherit
